version: '3.7'

services:

  mag_sql:
    image: mariadb
    container_name: "magratheaclouds-sql"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # - ./databases/mysql:/application
      - ./database:/home/backups
    env_file:
      - ./docker/.env
    ports:
      - 3306

  magrathea_cloud:
    hostname: cloud.magrathea.localhost.com
    container_name: "magrathea-cloud"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes: 
      - ./src:/var/www/html
      - ./logs:/var/www/logs
      - ./backups:/var/www/backups
      - ./medias:/var/www/medias
    ports:
      - 8080:80
      - 443
    env_file:
      - ./docker/.env

# helper containers:
  magrathea_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: magratheaclouds-dev_pma
    environment:
      PMA_HOST: mag_sql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - mag_sql
    ports:
      - 8183:80
