<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2024-04-01 14:01:19]

namespace MagratheaCloud\Crawl\Base;

use Magrathea2\MagratheaModelControl;

class CrawlControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaCloud\Crawl";
	protected static $modelName = "Crawl";
	protected static $dbTable = "crawls";
}
