<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2024-02-24 14:47:57]

namespace MagratheaCloud\File\Base;

use Magrathea2\iMagratheaModel;
use Magrathea2\MagratheaModel;

class FileBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name, $filename, $extension, $type, $size, $location, $shared_key, $apikey_id;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct(  $id=0  ){ 
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "files";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";
		$this->dbValues["filename"] = "string";
		$this->dbValues["extension"] = "string";
		$this->dbValues["type"] = "string";
		$this->dbValues["size"] = "int";
		$this->dbValues["location"] = "string";
		$this->dbValues["shared_key"] = "string";
		$this->dbValues["apikey_id"] = "string";
		$this->dbValues["created_at"] =  "datetime";
		$this->dbValues["updated_at"] =  "datetime";


	}

	public function GetControl() {
		return new \MagratheaCloud\File\Base\FileControlBase();
	}

	// >>> relations:

}
