<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2024-02-24 14:47:58]

namespace MagratheaCloud\File\Base;

use Magrathea2\MagratheaModelControl;

class FileControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaCloud\File";
	protected static $modelName = "File";
	protected static $dbTable = "files";
}
