<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2024-04-08 21:25:06]

namespace MagratheaCloud\File\Base;

use Magrathea2\iMagratheaModel;
use Magrathea2\MagratheaModel;

class FileBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name, $filename, $extension, $type, $mime, $size, $location, $location_id, $shared_key, $downloads, $apikey_id, $comments, $sent_at;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct(  $id=0  ){ 
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "files";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";
		$this->dbValues["filename"] = "string";
		$this->dbValues["extension"] = "string";
		$this->dbValues["type"] = "string";
		$this->dbValues["mime"] = "string";
		$this->dbValues["size"] = "int";
		$this->dbValues["location"] = "string";
		$this->dbValues["location_id"] = "int";
		$this->dbValues["shared_key"] = "string";
		$this->dbValues["downloads"] = "int";
		$this->dbValues["apikey_id"] = "string";
		$this->dbValues["comments"] = "text";
		$this->dbValues["sent_at"] = "datetime";
		$this->dbValues["created_at"] =  "datetime";
		$this->dbValues["updated_at"] =  "datetime";


	}

	public function GetControl() {
		return new \MagratheaCloud\File\Base\FileControlBase();
	}

	// >>> relations:

}
