<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2024-03-27 17:08:12]

namespace MagratheaCloud\Apikey\Base;

use Magrathea2\MagratheaModelControl;

class ApikeyControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaCloud\Apikey";
	protected static $modelName = "Apikey";
	protected static $dbTable = "apikey";
}
