<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2024-02-24 14:47:44]

namespace MagratheaCloud\Apikey\Base;

use Magrathea2\MagratheaModelControl;

class ApikeyControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaCloud\Apikey";
	protected static $modelName = "Apikey";
	protected static $dbTable = "apikey";
}
