<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2024-02-24 14:48:18]

namespace MagratheaCloud\Sharekey\Base;

use Magrathea2\MagratheaModelControl;

class SharekeyControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaCloud\Sharekey";
	protected static $modelName = "Sharekey";
	protected static $dbTable = "sharekeys";
}
