<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2024-04-05 22:52:48]

namespace MagratheaCloud\Folder\Base;

use Magrathea2\iMagratheaModel;
use Magrathea2\MagratheaModel;

class FolderBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name, $foldername, $location, $location_id, $shared_key, $apikey_id;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct(  $id=0  ){ 
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "folders";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";
		$this->dbValues["foldername"] = "string";
		$this->dbValues["location"] = "string";
		$this->dbValues["location_id"] = "int";
		$this->dbValues["shared_key"] = "string";
		$this->dbValues["apikey_id"] = "string";
		$this->dbValues["created_at"] =  "datetime";
		$this->dbValues["updated_at"] =  "datetime";


	}

	public function GetControl() {
		return new \MagratheaCloud\Folder\Base\FolderControlBase();
	}

	// >>> relations:

}
