<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2024-03-22 01:11:47]

namespace MagratheaCloud\Folder\Base;

use Magrathea2\MagratheaModelControl;

class FolderControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaCloud\Folder";
	protected static $modelName = "Folder";
	protected static $dbTable = "folders";
}
